### ISSUE TITLE
aiconfig 设置模型配置的时候报错

### ISSUE THREAD

**Issue by hellloveyy** [BuilderIO/ai-shell#117]
◇  设置配置:
│  模型

✖ Request failed with status code 404
    at createError (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

    ai-shell v1.0.10

**Comment by chen201724** [comment]
It could be a settings issue, please check your `OpenAI API Endpoint` config.
