### ISSUE TITLE
AI Shell fails

### ISSUE THREAD

**Issue by smmoulder** [BuilderIO/ai-shell#125]
Invalid character in header content ["Authorization"]
    at ClientRequest.setHeader (node:_http_outgoing:651:3)
    at new ClientRequest (node:_http_client:291:14)
    at Object.request (node:https:366:10)
    at RedirectableRequest._performRequest (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/follow-redirects/index.js:326:24)
    at new RedirectableRequest (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/follow-redirects/index.js:100:8)
    at Object.request (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/follow-redirects/index.js:532:14)
    at dispatchHttpRequest (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/openai/node_modules/axios/lib/adapters/http.js:242:25)
    at new Promise (<anonymous>)
    at httpAdapter (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/openai/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/usr/local/lib/node_modules/@builder.io/ai-shell/node_modules/openai/node_modules/axios/lib/core/dispatchRequest.js:58:10)

    ai-shell v1.0.10

    Please open a Bug report with the information above:

**Comment by chen201724** [comment]
This might be caused by incorrect `OpenAPI Key` settings.
