### ISSUE TITLE
Error when running sudo ai config set OPENAI_KEY=<my openi key goes here>

### ISSUE THREAD

**Issue by mightywomble** [BuilderIO/ai-shell#97]
Getting the following error

file:///usr/local/lib/node_modules/@builder.io/ai-shell/dist/cli.mjs:1079
    const value = cliConfig?.[key] ?? config[key];
                            ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by duronxx** [comment]
ai config set OPENAI_API_BASE=https://aa.xxx.top

✖ Invalid config property: OPENAI_API_BASE

ai config set OPENAI_API_BASE=   ，Please customize

**Comment by DmitriiCM** [comment]
I had the same issue on Ubuntu, the default nodejs version installed by apt is ancient old.

Install version 20 LTS, then everything works

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash`
`nvm install v20.13.0`

**Comment by jeon3029** [comment]
@DmitriiCM Thanks. It works for me!

```sh
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
$ source ~/.nvm/nvm.sh
$ nvm install v20.13.0
```


- ref : https://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm
